### ISSUE TITLE
concurrent/ProgressThreadedRTS.hs claims that `postGui` is needed, but that function is not used.

### ISSUE THREAD

**Issue by miguel-negrao** [haskell-gi/gi-gtk-examples#8]
The example says "Because Gtk+ is single threaded we have to be very careful to call Gtk+ only from the main GUI thread. So while it's ok to forkIO, any GUI actions in that thread have to be 'posted' to the main GUI thread using postGUI, or postGUIAsync as in the example here.", but then the actual code doesn't use postGUI, it uses idleAdd.

**Comment by garetxe** [comment]
Thanks a lot! I just fixed the documentation. (There is no need for postGUI in modern `gtk`, idleAdd is enough.)

**Comment by miguel-negrao** [comment]
Thanks for fixing ! 

So it is safe to call idleAdd from a haskell thread which might be on a different OS thread than the gtk thread ? If so, does that mean that internally idleAdd uses some mechanism to add the callback to the list of idle callbacks without the risk of a race condition, for instance via a mutex ? I understand that the whole point of using idleAdd is to make sure the calback is run in the gtk thread, but the action of adding a callback to a list from a different thread might itself present the risk of a race condition if care is not taken, might it not ?

**Comment by garetxe** [comment]
> If so, does that mean that internally idleAdd uses some mechanism to add the callback to the list of idle callbacks without the risk of a race condition, for instance via a mutex ?

Yes, that's right. `idleAdd` simply calls `g_idle_add` (the C function) internally, but this one uses [`g_source_attach`](https://docs.gtk.org/glib/method.Source.attach.html) internally, which is thread safe.

**Comment by miguel-negrao** [comment]
Great, that really clears things up. One more question if I may: adding a new callback for some signal via [on](https://hackage.haskell.org/package/haskell-gi-base-0.25.0/docs/Data-GI-Base-Signals.html#v:on)  from a different thread should also be done via `idleAdd`, correct ? Or is [on](https://hackage.haskell.org/package/haskell-gi-base-0.25.0/docs/Data-GI-Base-Signals.html#v:on) itself thread-safe ? 

edit: And also, are the functions in https://github.com/haskell-gi/haskell-gi/blob/master/gi-gtk-hs/src/Data/GI/Gtk/Threading.hs still needed ? `postGUISync` seems to do something similar to `idleAdd`.

edit2: `on` eventually [calls](https://hackage.haskell.org/package/haskell-gi-base-0.25.0/docs/src/Data.GI.Base.Signals.html#connectSignalFunPtr) `g_signal_connect_data` which internally [calls](https://gitlab.gnome.org/GNOME/glib/-/blob/main/gobject/gsignal.c#L2578) ` SIGNAL_LOCK ()` so perhaps it's thread-safe ?

**Comment by garetxe** [comment]
> on eventually calls g_signal_connect_data which internally calls SIGNAL_LOCK () so perhaps it's thread-safe ?

Yes, I believe that this is right, `on` should be thread safe. There may be bugs lurking here, as I don't think this code has been very tested in a multithreaded setting, but if there are bugs they should be fixable.

> And also, are the functions in https://github.com/haskell-gi/haskell-gi/blob/master/gi-gtk-hs/src/Data/GI/Gtk/Threading.hs still needed ? postGUISync seems to do something similar to idleAdd.

No, I think that for the most part you shouldn't need this. The basic rule is that `GLib` and the Haskell runtime are thread-safe, anything above that (such as `Gdk` or `Gtk`) are not, and should only be invoked from the main(loop) thread (using `idleAdd`).
